-- CREATE TABLE PUPPIES(
--     id serial primary key,
--     breed varchar(20),
--     description varchar(300),
--     price decimal,
--     image text
-- );

-- CREATE TABLE cart(
--     puppies_id integer references puppies(id)
-- )